### ISSUE TITLE
Duplicate job on Travis CI

### ISSUE THREAD

**Issue by svenfuchs** [manakai/perl-web-url#1]
hey there 👋 

i am running some build config validation tasks on Travis CI, and noticed a bunch of repositories on `manakai` are running an extra, duplicate job due to an empty `test` stage. future versions of our build config validation process will filter this extra job out, but i thought i'd notify you about this in case this is in any way intended behavior. if it is, could you please let me know what the purpose of it is?

e.g. this build https://travis-ci.org/manakai/perl-web-url/builds/657909148 has two jobs running against `perl: 5.26`.

that extra job currently is generated because of the otherwise empty job definition `{ "stage" : "test" }` on `jobs.include`. while our build config processing logic filters out duplicate jobs, this currently happens at a point where the default stage name `test` is not yet set to jobs that come out of the matrix expansion of the key `perl` (in this case). future versions of our build config processing logic will filter it out.

```json
   "perl" : [
      "5.26",
      "5.14"
   ],
   "jobs" : {
      "include" : [
         {
            "stage" : "test"
         },
         {
            "before_install" : "true",
            "install" : "true",
            "script" : "curl -f https://gist.githubusercontent.com/wakaba/ab553f86cd017e0cb28c6dbb5364b009/raw/travis-merge-job.pl | perl",
            "stage" : "merge"
         }
      ]
   }
```

unless there's a particular reason for keeping this job (in which case you'd need to make it unique, e.g. by providing a `name`), i'd recommend removing the otherwise empty job definition `{ "stage" : "test" }`  from `jobs.include`. the two jobs that come out of the matrix expansion `perl: 5.26` and `perl: 5.14` will still be assigned the default stage name `test`, and will still continue to be run as the first stage. See this build https://travis-ci.org/svenfuchs/test/builds/657913479 and this config https://travis-ci.org/svenfuchs/test/builds/657913479/config

**Comment by wakaba** [comment]
Duplication was not intentional.  I've updated `.travis.yml` of this repository as you recommended (and of other relevant repositories, in due course).

Thank you!
